config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"
  scope module: 'users' do
    resources :posts do
      resources :comments
    end
  end

  resources :posts do
    resources :likes
  end
  

  namespace :api do
    namespace :v1 do
      resources :posts do
        resources :comments
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :email, presence: true
  validates :password, presence: true
end

app/controllers/api/v1/application_controller.rb
module Api
    module V1
        class ApplicationController < ActionController::API
        end
    end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < Api::V1::ApplicationController
    def index
      @post = Post.find(params[:post_id])
      @comments = @post.comments
      render json: @comments, status: 200
    end
  
    def show
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
      if @comment
        render json: @comment, status: 200
      else
        render json: {error: "comment not found."}
      end
    end
  
    # def create
    #   @comment = Comment.new(comment_params)
    #   if @comment.save
    #     render json: @comment, status: 200
    #   else
    #     render json: {error: "comment not created"}
    #   end
    # end
  
    # def update
    #   @comment = Comment.find(params[:id])
    #   @comment.update(comment_params)
    #   render json: @comment, status: 200
    # end
  
    # def destroy
    #   @comment = Comment.find(params[:id])
    #   @comment.destroy
    #   render json: Comment.all 
    # end
    private
      def comment_params
        params.require(:comment).permit([:comment,:user_id,:post_id])
      end
  end
  

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::ApplicationController
    def index
      @posts = Post.all

      @posts = @posts.page(params[:page] || 1).per(params[:per] || 2)
      
      if params[:user_id]
        @posts = @posts.where(user_id: params[:user_id])
      end
      # @posts = filter(Post.all)
      render json: @posts, status: 200
    end
  
    def show
      @post = Post.find(params[:id])
      if @post
        render json: @post, status: 200
      else
        render json: {error: "post not found."}
      end
    end
  
    def create
      @post = Post.new(title: params[:title],body: params[:body],user_id: params[:user_id])
      if @post.save
        render json: @post, status: 200
      else
        render json: {error: "post not created"}
      end
    end
  
    def update
      @post = Post.find(params[:id])
      @post.update(title: params[:title],body: params[:body],user_id: params[:user_id])
      render json: @post, status: 200
    end
  
    def destroy
      @post = Post.find(params[:id])
      @post.destroy
      render json: Post.all 
    end
    private
      def post_params
        params.require(:post).permit([:title,:body,:user_id])
      end
      
      # def filter_params
      #   params.fetch(:filter, {})
      # end
      # def filter(relation)
      #   return relation unless filter_params.any?
      #   relation.where(filter_params)
      # end

      
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.page(params[:page] || 1).per(params[:per] || 2)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post  
  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @post.likes.create(user_id: current_user.id)
    end
    redirect_to post_path(@post)
  end
  private  
    def find_post
      @post = Post.find(params[:post_id])
    end
    def already_liked?
      Like.where(user_id: current_user.id, post_id: params[:post_id]).exists?
    end
end

app/controllers/users/comments_controller.rb
module Users
  class CommentsController < ApplicationController
    # before_action :authenticate_user!
    def create
      @post = Post.find(params[:post_id])
      p params
      # comment_params[:user_id] = current_user.id
      @comment = @post.comments.create(comment_params.merge(user_id: current_user.id))
      redirect_to post_path(@post)
    end

    def destroy
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
      @comment.destroy
        redirect_to post_path(@post), status: 303
    end

    private
      def comment_params
        params.require(:comment).permit(:comment)
      end
  end
end    

app/controllers/users/posts_controller.rb
module Users
  class PostsController < UsersController
    # before_action :authenticate_user!
    before_action :set_post, only: %i[ show edit update destroy ]
  
    # GET /posts or /posts.json
    def index
      # @posts = current_user.posts.page(params[:page] || 1).per(params[:per]  || 1)
      @page = (params[:page] || 1).to_i
      @per = (params[:per] || 1).to_i
      @posts = Post.offset(@per * (@page - 1)).limit(@per)
    end
  
    # GET /posts/1 or /posts/1.json
    def show
    end
  
    # GET /posts/new
    def new
      @post = current_user.posts.build
    end
  
    # GET /posts/1/edit
    def edit
    end
  
    # POST /posts or /posts.json
    def create
      @post = current_user.posts.build(post_params)
  
      respond_to do |format|
        if @post.save
          format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /posts/1 or /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /posts/1 or /posts/1.json
    def destroy
      @post.destroy
  
      respond_to do |format|
        format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def post_params
        params.require(:post).permit(:title, :body)
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </head>

  <div class="jumbotron" style="color: brown">
    <h1>Posts</h1>
  </div>

  <style>
    table, th, td {
      border: 1px solid black;
      border-collapse: collapse;
    }
    table.center{
      margin-left: auto; 
      margin-right: auto;
    }
    div{
      text-align:center; 
    }
    .bg{
      background-color: #1abc9c; /* Green */
      color: #ffffff;
    }
  </style>

  <body>
    <table class="center">
      <thead>
        <tr>
          <th>Title</th>
          <th>Body</th>
          <th>No. of likes</th>
        </tr>
      </thead>

      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= link_to post.title, post %></td>
            <td><%= link_to post.body, post %></td>
            <td><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div><%= paginate @posts %></div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <p class="navbar-text float-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>
      <%= button_to "Logout", destroy_user_session_path, method: :delete %>
      <%= link_to 'Edit profile', edit_user_registration_path %> 
    <% else %>
      <%= link_to "Sign up", new_user_registration_path  %> 
      <%= link_to "Login", new_user_session_path  %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/comments/_comment.html.erb
<div id="<%= dom_id comment %>">

  <p>
    <strong>Commenter:</strong>
    <%= (User.find(comment.user_id)).email %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.comment %>
  </p>


  <p>
  <%= link_to "Destroy Comment", [comment.post, comment], data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
              } %>
  </p>

</div>

app/views/users/posts/_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<style>
  div{
    text-align:center;
  }
</style>

<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  

  <div>
    <%= form.submit %>
  </div>
<% end %>
</html>

app/views/users/posts/_post.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>

<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}

table.center{
  margin-left: auto; 
  margin-right: auto;
}
div{
  text-align:center; 
}
</style>

<div id="<%= dom_id post %>">

<div>
  <p>User :<%= User.find(post.user_id).email %></p>

  <p>Title :<%= post.title %></p>
  <p>Body :<%= post.body %></p>
</div>

</div>
</html>

app/views/users/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/users/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<style>
  div{
    text-align:center;
  }
</style>

<div>
  <h1>Posts</h1>
</div>

<div id="posts">
  <% @posts.each do |post| %>
    
    <%= render post %>
    <p><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
    
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>


<%= link_to "New post", new_post_path %>
<div>
  <ul class="pager">
     <li class="previous <%= @page == 1 ? 'disabled' : '' %>">
       <div class="center">
         <%= link_to_if @page > 1, "<< Previous", posts_path(page: @page - 1) %>
       </div>
     </li>

     <li class="next <%= @page == (Post.count % @per == 0 ? Post.count / @per : (Post.count / @per) + 1) ? 'disabled' : '' %>">
         <div class="center">
           <%= link_to_if @page < (Post.count % @per == 0 ? Post.count / @per : (Post.count / @per) + 1), "Next >>", posts_path(page: @page + 1) %>
         </div>
     </li>
  </ul>


</div>

app/views/users/posts/new.html.erb
<style>
  div{
    text-align:center;
  }
</style>

<div>
  <h1>New post</h1>
</div>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/users/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </head>

  <style>
    div{
      text-align:center;
    }
    .bg{
      background-color: #000000; /* Green */
      color: #ffffff;
    }
  </style>

  <body>
    <div>
      <p>User :<%= User.find(@post.user_id).email %></p>
      <p>Title :<%= @post.title %></p>
      <p>Body :<%= @post.body %></p>
    </div>

    <div>
      <%= button_to 'Like', post_likes_path(@post), method: :post %>
      <p><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
    </div>

    <div>
      <%= link_to "Edit this post", edit_post_path(@post) %> |
      <%= link_to "Back to posts", posts_path %>
      <%= button_to "Destroy this post", @post, method: :delete %>
    </div>

    <div>
      <h2>Comments</h2>
    </div>

    <%= render @post.comments %>

    <div>
      <h3>Add a comment:</h3>
      <%= form_with model: [ @post, @post.comments.build ] do |form| %>
        <p>
          <%= form.label :comment %><br>
          <%= form.text_area :comment %>
        </p>
        <p>
          <%= form.submit %>
        </p>
      <% end %>
    </div>
  </body>
</html>